import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import api from '../api/client';
import { formatPrice } from '../components/ProductCard';

const STATUSES = ['PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED'];
const labels = { PENDING: 'Pending', PROCESSING: 'Processing', SHIPPED: 'Shipped', DELIVERED: 'Delivered', CANCELLED: 'Cancelled' };
const date = (value) => new Date(value).toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' });

export default function AdminOrdersPage() {
  const [orders, setOrders] = useState([]); const [search, setSearch] = useState(''); const [filter, setFilter] = useState('ALL'); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [updating, setUpdating] = useState(null);
  const load = () => { setLoading(true); setError(''); api.get('/api/admin/orders').then((response) => setOrders(response.data?.orders || [])).catch(() => setError('Unable to load orders.')).finally(() => setLoading(false)); };
  useEffect(() => { load(); }, []);
  const filtered = useMemo(() => orders.filter((order) => { const query = search.toLowerCase().trim(); return (filter === 'ALL' || order.status === filter) && (!query || String(order.id).includes(query) || order.user?.name?.toLowerCase().includes(query) || order.user?.email?.toLowerCase().includes(query)); }), [filter, orders, search]);
  const updateStatus = async (id, status) => { try { setUpdating(id); await api.patch(`/api/admin/orders/${id}/status`, { status }); setOrders((current) => current.map((order) => order.id === id ? { ...order, status } : order)); } catch { setError('Unable to update order status.'); } finally { setUpdating(null); } };
  if (loading) return <div className="admin-state">Loading orders...</div>;
  if (error && !orders.length) return <div className="admin-state admin-error" role="alert"><strong>Orders unavailable</strong><span>{error}</span><button className="btn btn-secondary" type="button" onClick={load}>Try again</button></div>;
  return <div className="admin-page"><div className="admin-page-heading"><div><span className="eyebrow">Operations</span><h1>Orders</h1><p className="muted">Review customers’ orders and keep fulfilment moving.</p></div></div>{error && <div className="alert error" role="alert">{error}</div>}<section className="admin-toolbar"><div className="search-field"><label htmlFor="admin-order-search">Search orders</label><input id="admin-order-search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search ID, customer, or email" /></div><div className="filter-field"><label htmlFor="admin-order-status">Status</label><select id="admin-order-status" value={filter} onChange={(event) => setFilter(event.target.value)}><option value="ALL">All statuses</option>{STATUSES.map((status) => <option key={status} value={status}>{labels[status]}</option>)}</select></div></section>{filtered.length === 0 ? <div className="admin-state"><strong>No orders found</strong><span>Try changing the search or status filter.</span></div> : <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Order</th><th>Customer</th><th>Date</th><th>Items</th><th>Total</th><th>Status</th><th>Action</th></tr></thead><tbody>{filtered.map((order) => <tr key={order.id}><td><Link className="admin-order-link" to={`/orders/${order.id}`}>#{order.id}</Link></td><td><strong>{order.user?.name || 'Unknown'}</strong><small>{order.user?.email}</small></td><td>{date(order.createdAt)}</td><td>{(order.items || []).reduce((sum, item) => sum + Number(item.quantity || 0), 0)}</td><td>{formatPrice(order.total)}</td><td><span className={`order-status status-${order.status.toLowerCase()}`}>{labels[order.status] || order.status}</span></td><td><select aria-label={`Update order ${order.id} status`} value={order.status} disabled={updating === order.id} onChange={(event) => updateStatus(order.id, event.target.value)}>{STATUSES.map((status) => <option key={status} value={status}>{labels[status]}</option>)}</select></td></tr>)}</tbody></table></div>}</div>;
}
