import { useEffect, useMemo, useState } from 'react';
import api from '../api/client';
import { ProductImage, formatPrice } from '../components/ProductCard';

const emptyForm = { name: '', description: '', price: '', image: '', stock: '', category: '' };

export default function AdminProductsPage() {
  const [products, setProducts] = useState([]); const [search, setSearch] = useState(''); const [category, setCategory] = useState('ALL'); const [form, setForm] = useState(emptyForm); const [editing, setEditing] = useState(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const load = () => { setLoading(true); api.get('/api/admin/products').then((response) => setProducts(response.data?.products || [])).catch(() => setError('Unable to load products.')).finally(() => setLoading(false)); };
  useEffect(() => { load(); }, []);
  const categories = useMemo(() => [...new Set(products.map((product) => product.category).filter(Boolean))].sort(), [products]);
  const filtered = products.filter((product) => { const query = search.toLowerCase().trim(); return (category === 'ALL' || product.category === category) && (!query || `${product.name} ${product.category} ${product.description}`.toLowerCase().includes(query)); });
  const change = (event) => setForm((current) => ({ ...current, [event.target.name]: event.target.value }));
  const edit = (product) => { setEditing(product.id); setForm({ name: product.name, description: product.description, price: product.price, image: product.image, stock: product.stock, category: product.category }); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const reset = () => { setEditing(null); setForm(emptyForm); };
  const save = async (event) => { event.preventDefault(); try { setSaving(true); setError(''); const response = editing ? await api.put(`/api/admin/products/${editing}`, form) : await api.post('/api/admin/products', form); setProducts((current) => editing ? current.map((product) => product.id === editing ? response.data.product : product) : [response.data.product, ...current]); reset(); } catch (err) { setError(err.response?.data?.message || 'Unable to save product.'); } finally { setSaving(false); } };
  const remove = async (product) => { if (!window.confirm(`Delete ${product.name}?`)) return; try { await api.delete(`/api/admin/products/${product.id}`); setProducts((current) => current.filter((item) => item.id !== product.id)); } catch (err) { setError(err.response?.data?.message || 'Unable to delete product.'); } };
  if (loading) return <div className="admin-state">Loading products...</div>;
  return <div className="admin-page"><div className="admin-page-heading"><div><span className="eyebrow">Catalog</span><h1>Products</h1><p className="muted">Keep the storefront collection current.</p></div></div>{error && <div className="alert error" role="alert">{error}</div>}<section className="admin-product-editor"><div className="admin-panel-heading"><div><span className="eyebrow">{editing ? 'Edit product' : 'New product'}</span><h2>{editing ? 'Update product' : 'Add a product'}</h2></div></div><form className="admin-form" onSubmit={save}>{['name', 'description', 'image', 'category', 'price', 'stock'].map((field) => <div className={`field ${field === 'description' ? 'field-wide' : ''}`} key={field}><label htmlFor={`product-${field}`}>{field[0].toUpperCase() + field.slice(1)}</label>{field === 'description' ? <textarea id={`product-${field}`} name={field} value={form[field]} onChange={change} required rows="3" /> : <input id={`product-${field}`} name={field} type={field === 'price' || field === 'stock' ? 'number' : 'text'} step={field === 'price' ? '0.01' : undefined} min={field === 'price' ? '0.01' : field === 'stock' ? '0' : undefined} value={form[field]} onChange={change} required />}</div>)}<div className="admin-form-actions"><button className="btn btn-primary" disabled={saving}>{saving ? 'Saving...' : editing ? 'Save changes' : 'Add product'}</button>{editing && <button className="btn btn-secondary" type="button" onClick={reset}>Cancel</button>}</div></form></section><section className="admin-panel"><div className="admin-toolbar"><div className="search-field"><label htmlFor="admin-product-search">Search products</label><input id="admin-product-search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search name, category, description" /></div><div className="filter-field"><label htmlFor="admin-product-category">Category</label><select id="admin-product-category" value={category} onChange={(event) => setCategory(event.target.value)}><option value="ALL">All categories</option>{categories.map((item) => <option key={item} value={item}>{item}</option>)}</select></div></div>{filtered.length === 0 ? <div className="admin-state"><strong>No products found</strong></div> : <div className="admin-product-list">{filtered.map((product) => <article className="admin-product-row" key={product.id}><ProductImage product={product} className="admin-product-image" /><div><strong>{product.name}</strong><span>{product.category} · {product.stock} in stock</span></div><strong>{formatPrice(product.price)}</strong><div className="admin-row-actions"><button className="btn btn-secondary" type="button" onClick={() => edit(product)}>Edit</button><button className="btn btn-danger" type="button" onClick={() => remove(product)}>Delete</button></div></article>)}</div>}</section></div>;
}
